[book]
title = "The Fram Language"
description = "The documentation for the Fram programming language."
language = "en"

[preprocessor.katex]
after = ["links"]

[preprocessor.treesitter]
command = "mdbook-treesitter"
languages = ["fram"]

